### ISSUE TITLE
Whitescreen On iOS target

### ISSUE THREAD

**Issue by onatbas** [away3d/away3d-examples-openfl#2]
on Mac and Android targets, Load3DS example works great. on iOS target , all i get after black splash screen in is a complete white screen, no error is thrown.
Just this is traced over and over again > Context3D.hx:424: FRAMEBUFFER_COMPLETE
But i think thats expected behaviour?

White is my application background color btw. if you set to green, it is first black, and then green. Something is being disposed?

**Comment by shintiger** [comment]
Greg209 could you describe more? I want to debug this problem on away3d AIR version.
Even OpenGL solution, I don't know what keywords should I search for this shadow problem on iOS

**Comment by Greg209** [comment]
Hi. This fork is very out of date now as the openfl versions of away3d and the examples have been pulled into the the openfl github repository. If possible, I suggest you try https://github.com/openfl/away3d & https://github.com/openfl/away3d-samples for the latest code. You'll probably need an up-to-date version of OpenFL too.

It's been a while since I tested the code so this may or may not be an issue anymore with those versions.

**Comment by onatbas** [comment]
Oh, time flies.. 

As I was able to fix it for my own case at that time, and given this fork is pretty out of date, and the code at openfl repository solves this, I think I can close this issue.
